blank_issues_enabled: false
contact_links:
   - name: "💬 Discord Community"
     url: "https://dsc.gg/k4-fanbase"
     about: "Join my Discord server for support, discussions, and community help"
   - name: "🌐 Website"
     url: "https://k4ryuu.com"
     about: "My website with some information"
